version: "3.7"
services:
  flask:
    container_name: flask-pebrassos
    build: .
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
      - FLASK_APP="entrypoint"
      - FLASK_ENV="production"
      - APP_SETTINGS_MODULE=config.prod

      - MYSQL_USER= "admin"
      - PASSWORD= "1234"
      - HOST= "localhost"
      - DATABASE= "Pebrassos"
      - PORT= "3308"

    expose:
      - 8081
  nginx:
    container_name: nginx-pebrassos
    build: ./nginx
    restart: always
    ports:
      - "8005:80"
  db:
    container_name: db-pebrassos
    image: mysql:5.7
    ports:
      - "32001:3308"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro