version: "3.7"
services:
  flask_Pebrassos:
    build: .
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
      - FLASK_APP="entrypoint"
      - FLASK_ENV="production"
      - APP_SETTINGS_MODULE="config.prod"
    expose:
      - 8081
  nginx_Pebrassos:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8005:80"
  db_Pebrassos:
    image: mysql:5.7
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro